language: cpp
notifications:
    email: false
script:
    - echo Current commit is $TRAVIS_COMMIT
    - echo Current commit range is $TRAVIS_COMMIT_RANGE
    - export FILES_CHANGED=$(git diff --name-only $TRAVIS_COMMIT_RANGE); echo $FILES_CHANGED
    - echo $FILES_CHANGED
